version: "3"
services: 
    mipagina01:
        image: php:7.2-apache
        restart: always
        ports: 
            - "8084:80"
        volumes: 
            - ./data:/var/www/html/
        container_name: cont_mipagina