version: "3"
services: 
    mipagina01:
        build: .
        image: img_mipagina:v1
        restart: always
        ports: 
            - "8084:80"
        environment: 
            title_page: 'titulo desde docker compose'
        container_name: cont_mipagina